// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkvknihyyljdslywitez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrdmtuaWh5eWxqZHNseXdpdGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Mzc2MjEsImV4cCI6MjA3MDExMzYyMX0.-YwQG9Nrx0RSEOjy_kmkRrpG7kxdlEstCjyYuxG8RDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});